# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca8bfcba7932136ad5722c3d9ab54c83477abcc70875909fe9bfb9e8627ab7649ad83abbffd733f4c2bad079ae92c13cec451b2cb4d4f0407b8ba9b44198df96

test:
  secret_key_base: decfb738356af4a4359cb6c0078cd59cd71fc56f184e78d4f728660cd1f96860de263fe25dbe69958ce69aece760e2b1a1b95bf56f552acaadef3cdcb9c6b3c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
